name: expenso
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: 3.10.0-290.1.beta

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  google_fonts: ^6.3.3
  intl: ^0.20.2
  uuid: ^4.5.2
  fl_chart: ^1.1.1
  http: ^1.6.0
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"

  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
